In [28]:
# ============================================
# 0) PREREQS
# ============================================
import pandas as pd
import numpy as np
import re

# Display settings for quick inspection in notebooks
pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 180)

# ============================================
# 1) LOAD RAW DATA
# ============================================
# Point to your raw CSV. Keep it in the same folder as the notebook or give a full path.
RAW = "customer_shopping_behavior.csv"
df = pd.read_csv(RAW, low_memory=False)

# Quick sanity check: shape and a small preview
print("Raw shape:", df.shape)
df.head(5)

Raw shape: (3900, 18)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [29]:
# ============================================
# 2) INITIAL DATA PROFILING
# ============================================
# Objective: understand basic schema, missingness, and cardinality drivers.

# Data types and non-null counts
df.info()

# Top columns by missing values
df.isna().sum().sort_values(ascending=False).head(10)

# Highest-cardinality columns (often IDs or free text)
df.nunique(dropna=True).sort_values(ascending=False).head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

Customer ID               3900
Purchase Amount (USD)       81
Age                         53
Location                    50
Previous Purchases          50
Review Rating               26
Color                       25
Item Purchased              25
Frequency of Purchases       7
Shipping Type                6
dtype: int64

In [30]:
# ============================================
# 3) STANDARDIZE COLUMN NAMES
# ============================================
# Rationale: stable snake_case column names reduce bugs in SQL/Python/BI.
# - Trim whitespace
# - Replace spaces and separators with underscores
# - Lowercase
# - Remove non-alphanumeric characters

def to_snake(s: str) -> str:
    s = re.sub(r'[\s\-/]+', '_', str(s).strip())   # normalize common separators to "_"
    s = re.sub(r'[^0-9a-zA-Z_]', '', s)            # drop special chars
    s = re.sub(r'__+', '_', s)                      # collapse multiple underscores
    return s.lower()

df.columns = [to_snake(c) for c in df.columns]
print("Standardized columns:", list(df.columns))

Standardized columns: ['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount_usd', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'promo_code_used', 'previous_purchases', 'payment_method', 'frequency_of_purchases']

In [31]:
# ============================================
# 3) STANDARDIZE COLUMN NAMES
# ============================================
# Rationale: stable snake_case column names reduce bugs in SQL/Python/BI.
# - Trim whitespace
# - Replace spaces and separators with underscores
# - Lowercase
# - Remove non-alphanumeric characters

def to_snake(s: str) -> str:
    s = re.sub(r'[\s\-/]+', '_', str(s).strip())   # normalize common separators to "_"
    s = re.sub(r'[^0-9a-zA-Z_]', '', s)            # drop special chars
    s = re.sub(r'__+', '_', s)                      # collapse multiple underscores
    return s.lower()

df.columns = [to_snake(c) for c in df.columns]
print("Standardized columns:", list(df.columns))

Standardized columns: ['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount_usd', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'promo_code_used', 'previous_purchases', 'payment_method', 'frequency_of_purchases']

In [32]:
# ============================================
# 4) PROTECT IDENTIFIERS FROM NUMERIC COERCION
# ============================================
# Rationale: IDs often contain digits but should remain strings to preserve leading zeros.
# Edit this set to match your schema.
protected_ids = {"customer_id"}

In [33]:
# ============================================
# 5) COERCE NUMERIC-LIKE TEXT COLUMNS
# ============================================
# Rationale: math on strings breaks KPIs; convert where it's clearly numeric.
# Rule: if >=90% of non-empty values parse as numbers, convert the column to numeric.

for c in df.columns:
    if df[c].dtype == object and c not in protected_ids:
        # Try parsing numbers; remove commas like "1,234"
        parsed = pd.to_numeric(df[c].astype(str).str.replace(",", ""), errors="coerce")
        # If enough values are numeric, we convert the whole column
        if parsed.notna().mean() >= 0.90:
            df[c] = parsed

In [34]:
# ============================================
# 6) NORMALIZE SIMPLE BOOLEANS AND TRIM STRINGS
# ============================================
# Rationale: standardize "Yes/No", "True/False", and remove accidental spaces.

def normalize_text_or_bool(x):
    if isinstance(x, str):
        s = x.strip().lower()
        if s in {"yes", "y", "true", "t", "1"}:  return True
        if s in {"no", "n", "false", "f", "0"}:  return False
        return x.strip()  # leave text as trimmed string
    return x

for c in df.columns:
    if df[c].dtype == object:
        df[c] = df[c].map(normalize_text_or_bool)

In [35]:
# ============================================
# 7) DROP EXACT DUPLICATE ROWS
# ============================================
# Rationale: identical duplicates inflate KPIs and mislead EDA.

before = len(df)
df = df.drop_duplicates().reset_index(drop=True)
after = len(df)
print(f"Duplicates removed: {before - after} (from {before} to {after})")

Duplicates removed: 0 (from 3900 to 3900)

In [36]:
# ============================================
# 8) IMPUTATION POLICY (CHOOSE)
# ============================================
# Rationale: missing values can block some KPIs. You decide the policy.
# - Set IMPUTE=False for transparency in learning projects (keep NaN, handle per metric)
# - Set IMPUTE=True for a quick, pragmatic fill to move fast on dashboards
# Show only columns that contain at least one missing value
missing_cols = df.columns[df.isna().any()]
print("Columns with missing values:")
print(list(missing_cols))

IMPUTE = False  # <<<<<<<<<<<<<< Flip to True if you want median/mode fills

if IMPUTE:
    for c in df.columns:
        if pd.api.types.is_numeric_dtype(df[c]):
            # Median is robust to outliers
            df[c] = df[c].fillna(df[c].median())
        elif pd.api.types.is_datetime64_any_dtype(df[c]):
            # Use most frequent date to preserve seasonality where possible
            m = df[c].mode(dropna=True)
            if len(m) > 0:
                df[c] = df[c].fillna(m.iloc[0])
        else:
            # Mode for categoricals; "Unknown" fallback protects downstream joins
            m = df[c].mode(dropna=True)
            df[c] = df[c].fillna(m.iloc[0] if len(m) > 0 else "Unknown")

Columns with missing values:
['review_rating']

In [37]:
# ============================================
# 9) OUTLIER SCAN (DETECT ONLY, NO REMOVAL)
# ============================================
# Rationale: highlight suspicious values. Removal is a business decision.

outlier_rows = []
for c in df.columns:
    if pd.api.types.is_numeric_dtype(df[c]):
        s = df[c].astype(float)
        mu = s.mean()
        sd = s.std(ddof=0)
        if sd and not np.isnan(sd):
            z = (s - mu) / sd
            n_out = int((z.abs() > 4).sum())  # count extreme values
        else:
            n_out = 0
        outlier_rows.append({"column": c, "mean": mu, "std": sd, "num_outliers_|z|>4": n_out})

outlier_report = pd.DataFrame(outlier_rows).sort_values("num_outliers_|z|>4", ascending=False)
print("Potential outliers (top 10):")
outlier_report.head(18)

Potential outliers (top 10):

                column         mean          std  num_outliers_|z|>4
0          customer_id  1950.500000  1125.832988                   0
1                  age    44.068462    15.205639                   0
2  purchase_amount_usd    59.764359    23.682355                   0
3        review_rating     3.750065     0.716890                   0
4  subscription_status     0.270000     0.443959                   0
5     discount_applied     0.430000     0.495076                   0
6      promo_code_used     0.430000     0.495076                   0
7   previous_purchases    25.351538    14.445273                   0

In [38]:
# ============================================
# 10) SAVE CLEANED DATASET
# ============================================
# Output file powering all downstream KPIs, SQL, and BI.
CLEAN = "customer_shopping_behavior_clean.csv"
df.to_csv(CLEAN, index=False)
print("Cleaned dataset saved to:", CLEAN)

Cleaned dataset saved to: customer_shopping_behavior_clean.csv

In [39]:
# ============================================
# 11) BUILD A LIGHTWEIGHT DATA DICTIONARY
# ============================================
# Rationale: share schema, types, non-null counts, and uniqueness with collaborators.

data_dict = pd.DataFrame({
    "column": df.columns,
    "dtype": [str(df[c].dtype) for c in df.columns],
    "non_null_count": [int(df[c].notna().sum()) for c in df.columns],
    "unique_values": [int(df[c].nunique(dropna=True)) for c in df.columns],
})
data_dict.to_csv("customer_shopping_behavior_data_dictionary.csv", index=False)
print("Data dictionary saved to: customer_shopping_behavior_data_dictionary.csv")
data_dict.head(12)

Data dictionary saved to: customer_shopping_behavior_data_dictionary.csv

                 column    dtype  non_null_count  unique_values
0           customer_id    int64            3900           3900
1                   age    int64            3900             53
2                gender   object            3900              2
3        item_purchased   object            3900             25
4              category   object            3900              4
5   purchase_amount_usd    int64            3900             81
6              location   object            3900             50
7                  size   object            3900              4
8                 color   object            3900             25
9                season   object            3900              4
10        review_rating  float64            3863             26
11  subscription_status     bool            3900              2

In [40]:
# ============================================
# 12) FINAL SANITY CHECKS
# ============================================
# Re-load the saved file to confirm it round-trips correctly
test = pd.read_csv("customer_shopping_behavior_clean.csv", nrows=5)
print("Reloaded preview:")
test

# High-level describe to spot obvious anomalies
df.describe(include="all").T.head(12)

Reloaded preview:

                      count unique       top  freq       mean          std   min     25%     50%      75%     max
customer_id          3900.0    NaN       NaN   NaN     1950.5  1125.977353   1.0  975.75  1950.5  2925.25  3900.0
age                  3900.0    NaN       NaN   NaN  44.068462    15.207589  18.0    31.0    44.0     57.0    70.0
gender                 3900      2      Male  2652        NaN          NaN   NaN     NaN     NaN      NaN     NaN
item_purchased         3900     25    Blouse   171        NaN          NaN   NaN     NaN     NaN      NaN     NaN
category               3900      4  Clothing  1737        NaN          NaN   NaN     NaN     NaN      NaN     NaN
purchase_amount_usd  3900.0    NaN       NaN   NaN  59.764359    23.685392  20.0    39.0    60.0     81.0   100.0
location               3900     50   Montana    96        NaN          NaN   NaN     NaN     NaN      NaN     NaN
size                   3900      4         M  1755        NaN          NaN   NaN     NaN     NaN      NaN     NaN
color                  3900     25     Olive   177        NaN          NaN   NaN     NaN     NaN      NaN     NaN
season                 3900      4    Spring   999        NaN          NaN   NaN     NaN     NaN      NaN     NaN
review_rating        3863.0    NaN       NaN   NaN   3.750065     0.716983   2.5     3.1     3.8      4.4     5.0
subscription_status    3900      2     False  2847        NaN          NaN   NaN     NaN     NaN      NaN     NaN

In [41]:
# pandas will help us read files (CSV)
import pandas as pd

# SQLAlchemy is the bridge between Python and PostgreSQL
from sqlalchemy import create_engine

In [42]:
# This is your PostgreSQL username (default = postgres)
user = "postgres"

# Put your PostgreSQL PASSWORD here (the one you chose during installation)
password = "123456789"   # ← replace this

# PostgreSQL runs locally on your computer
host = "localhost"

# This is the default PostgreSQL port
port = "5432"

# This is the name of the database you created in pgAdmin
dbname = "retail_data"

In [43]:
# This creates the exact URL needed to connect Python → PostgreSQL
# Format: postgresql://username:password@host:port/database_name
connection_url = f"postgresql://{user}:{password}@{host}:{port}/{dbname}"

# We print it to check if everything looks OK (optional)
print(connection_url)

postgresql://postgres:123456789@localhost:5432/retail_data

In [44]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\rezgu\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\rezgu\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\rezgu\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rezgu\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [45]:
import pandas as pd
from sqlalchemy import create_engine

# ---- STEP 1: PostgreSQL connection parameters ----
username = "postgres"           # default PostgreSQL user
password = "123456789"          # <-- your password
host = "localhost"              # local
port = "5432"                   # default
database = "retail_data"        # your database

# ---- STEP 2: Create engine using EXPLICIT psycopg2 driver ----
#    THIS is the correct format used by the other guy:
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# ---- STEP 3: Test the connection ----
test = pd.read_sql("SELECT 1 AS test_col;", engine)
print(test)

   test_col
0         1

In [46]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior_clean.csv")
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,True,Express,True,True,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,True,Express,True,True,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,True,Free Shipping,True,True,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,True,Next Day Air,True,True,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,True,Free Shipping,True,True,31,PayPal,Annually

In [47]:
df.to_sql("sales", engine, index=False, if_exists="replace")

900

In [27]:
pd.read_sql("SELECT COUNT(*) FROM sales;", engine)

   count
0   3900